# Generated by Django 4.2.23 on 2025-06-16 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_orderdetail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderdetail',
            old_name='stripe_payment_intent_id',
            new_name='stripe_payment_intent',
        ),
    ]
