# Generated by Django 4.2.23 on 2025-06-16 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_orderdetail_stripe_payment_intent'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetail',
            name='stripe_session_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
